### ISSUE TITLE
Is there instructions on how to install this?

### ISSUE THREAD

**Issue by stupid48** [eyolas/key-auth-referer#1]
I'm trying to run luarocks make on the plugins folder and I'm getting

Error: Argument missing: please specify a rockspec to use on current directory.

Is there a rockspec for this?

**Comment by eyolas** [comment]
Hi,

I don't use rockspec for the moment (but you can propose a PR )

I use KONG_LUA_PACKAGE_PATH and KONG_CUSTOM_PLUGINS

For example my DockerFile:
```
FROM kong:0.10.3

RUN mkdir -p /usr/local/custom/kong/plugins

ADD key-auth-referer /usr/local/custom/kong/plugins/key-auth-referer

ADD referer /usr/local/custom/kong/plugins/referer

ENV KONG_LUA_PACKAGE_PATH=$KONG_LUA_PACKAGE_PATH;/usr/local/custom/?.lua;;

ENV KONG_CUSTOM_PLUGINS=key-auth-referer,referer

COPY custom-docker-entrypoint.sh /custom-docker-entrypoint.sh

ENTRYPOINT ["/custom-docker-entrypoint.sh"]

EXPOSE 8000 8443 8001 3946
CMD ["kong", "start", "--vv"]
```

**Comment by stupid48** [comment]
Weird.  I tried using the environment variables and I'm still getting: 

I'm running 0.12.1 by the way...
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:51: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:165: referer plugin is enabled but not installed;
module 'kong.plugins.referer.handler' not found:No LuaRocks module found for kong.plugins.referer.handler

**Comment by stupid48** [comment]
I got it working.  I did my own rockspec and finally figured it out.  Thanks for responding though...
