### ISSUE TITLE
Getting error 500 when using plugin.

### ISSUE THREAD

**Issue by stupid48** [eyolas/key-auth-referer#2]
Hi there,
So on version 0.12.1 of Kong, they don't support "kong.tools.database_cache" any more.

I'm reading in the upgrade doc regarding this but I'm not much of a programmer.  I found it here:

https://github.com/Kong/kong/blob/master/UPGRADE.md

Would it be possible to update the code to support these changes?

Thanks, Chris

**Comment by eyolas** [comment]
I'm updating.

I think it's over next week.

**Comment by stupid48** [comment]
Thanks.  Much appreciated.

**Comment by eyolas** [comment]
Done in  v2.0

For help my dockerfile:
```
FROM kong:0.12.1

RUN yum install -y unzip git

RUN luarocks install --verbose kong-plugin-key-auth-referer

ENV KONG_CUSTOM_PLUGINS=key-auth-referer

EXPOSE 8000 8443 8001 3946
CMD ["kong", "start", "--vv"]
```
